### ISSUE TITLE
Field colors

### ISSUE THREAD

**Issue by ChristinaBJacob** [WiestDaessle/CheckoutBin#2]
When we are changing the displayed field on the workbench, the channel colors come back to default. 

Would it be possible, when we are changing the color of channels, that it changes it for all fields of the well ?

**Comment by WiestDaessle** [comment]
Will look into locking the dynamic if a file from same well is already loaded,

**Comment by WiestDaessle** [comment]
Christina the upcoming version should close this issue, and also add the synchronicity of color changing:
Either the whole plate in current workbench is changed together, or you can select multiple wells and by drag&drop while maintaining ctrl on the keyboard, will get a new joint control spécifically for the selection (decorrelated from the rest of the data).

**Comment by ChristinaBJacob** [comment]
It's great ! Thank you so much !
