### ISSUE TITLE
Threshold synchronization for all loaded plates

### ISSUE THREAD

**Issue by johanneswilbertz** [WiestDaessle/CheckoutBin#20]
Hi!
It would be great if different plates could be compared more easily if the selected threshold would be applied to all plates equally. Currently, I believe each plate has its own threshold settings. Especially during screen QC this would help a lot to quickly visually inspect and compare intensities of several plates.
Thanks!
Johannes

**Comment by WiestDaessle** [comment]
Can you try options -> shared intensities ? 

Should do the trick :)

**Comment by johanneswilbertz** [comment]
Aha :) That works!
