### ISSUE TITLE
Channel/Mask name display

### ISSUE THREAD

**Issue by ChristinaBJacob** [WiestDaessle/CheckoutBin#3]
Would it be possible to display the name of each masks and/or channels next to the tickboxes in Image Controls ?

**Comment by WiestDaessle** [comment]
If we can determine where this data is stored on the images metadata & ensure the link/coherency it could be easy,
I think it might sit in the crosstalk_parameter.xml file.
If you can confirm this :)

**Comment by ChristinaBJacob** [comment]
For the Channel labels:
I think the crosstlak_parameter.xml file is a matrix to correct for fluorescent signal leaks from defined fluorophores into all the possible channels.
I'll look in the files more specifically next week to extract the acquisition channels.

For the Mask labels:
Would it be also possible to do it within the analysis processes ? 
For example in DM1, it would be great if we could see a label "nuclei total", "fusion area" (or whatever the name is in the code) next to the corresponding tickboxes ?

EDIT: I don't know if I'm allowed to insert a picture here... Let me know and I can add it to illustrate what I mean.

**Comment by WiestDaessle** [comment]
Ok, I got it! Yes labels can be set when data comes from a plug-in, I need to update the plugin api & display.

It's clarified, I was thinking of experiment images not the output of plugin.

**Comment by WiestDaessle** [comment]
Update to checkout will allow the plugin's creator to set this up, i'have told the devs about this feature, once they tried it it will be available.
