### ISSUE TITLE
Field alignment when partial well is acquired

### ISSUE THREAD

**Issue by ChristinaBJacob** [WiestDaessle/CheckoutBin#7]
Problem of field alignment when some fields are empty in the acquired well.

Data: K:\BTSData\MeasurementData\CJ\20201005-CP-U2OS-DRC-20XLWD-noAF-centrifuge_20201012_152607

**Comment by ChristinaBJacob** [comment]
Also this (same plate imaged on 2 different acquisition but the fields are not at the good position when comparing the wells):
![image](https://user-images.githubusercontent.com/68071598/95962117-42e79d00-0e06-11eb-9469-61b45a308a87.png)

Data: 
K:\BTSData\MeasurementData\CJ\20201005-CP-U2OS-DRC-20XLWD-noAF-centrifuge_20201012_152607
K:\BTSData\MeasurementData\CJ\20201005-CP-U2OS-DRC-20XLWD-noAF_20201012_144823

**Comment by WiestDaessle** [comment]
Fixed in the 1.5R1, well position was recomputed for each well (with globabl incoherencies) and messing up with fields positions
