### ISSUE TITLE
Pack/Unpack display problem

### ISSUE THREAD

**Issue by ChristinaBJacob** [WiestDaessle/CheckoutBin#8]
It's me again !

I load a screen with the "Unpack automatically" option OFF, then open a field on the workbench, unpack it and:
![image](https://user-images.githubusercontent.com/68071598/95972148-66184980-0e12-11eb-9173-36c08b4bcdd2.png)

**Comment by WiestDaessle** [comment]
Fixed in 1.5R1 release, was an issues with offseting the channels, data set was Channel 1 & 3 from µscope some code part where still assuming continuity of channels.
