### ISSUE TITLE
Software crash when displaying after computation

### ISSUE THREAD

**Issue by ChristinaBJacob** [WiestDaessle/CheckoutBin#9]
When trying to display the different calculated masks (display = 1):
The computation works fine then when trying to display, Checkout takes an unusual long time then just quits.

I cannot reproduce the problem but it happened with DM1 plugin, with 2 or 3 channels, with different thresholds, on different plates...

**Comment by WiestDaessle** [comment]
Have been checking on this, should be fixed in the next release,
